name: solo_sis_loader

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - sunpy
  - sunpy-soar
  - xarray
  - pytest-astropy
  - pytest-sugar
  - pip
  - pip:
      - cdflib
